Update circleci config formatting

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,109 +1,109 @@
 version: 2
 jobs:
-    cypress/install:
-        docker:
-            - image: cypress/base:10
-        steps:
-            - checkout
-            - restore_cache:
-                  keys:
-                      - cache-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
-            - run:
-                  name: Check if package-lock.json exists
-                  command: |
-                      if [ ! -e ./package-lock.json ]; then
-                        echo "The Cypress orb uses 'npm ci' to install 'node_modules', which requires a 'package-lock.json'."
-                        echo "A 'package-lock.json' file was not found. Please run 'npm install' in your project,"
-                        echo "and commit 'package-lock.json' to your repo."
-                        exit 1
-                      fi
-                  working_directory: ''
-            - run:
-                  name: Npm CI
-                  command: npm ci
-                  working_directory: ''
-            - run:
-                  command: npx cypress verify
-                  working_directory: ''
-            - save_cache:
-                  key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
-                  paths:
-                      - ~/.npm
-                      - ~/.cache
-            - persist_to_workspace:
-                  root: ~/
-                  paths:
-                      - project
-                      - .cache/Cypress
-    Cypress tests:
-        docker:
-            - image: cypress/base:10
-        parallelism: 2
-        steps:
-            - run:
-                  command:
-                      echo "Assuming dependencies were installed using cypress/install
-                      job"
-            - attach_workspace:
-                  at: ~/
-            - run:
-                  name: Start
-                  command: npm run start
-                  background: true
-                  working_directory: ''
-            - run:
-                  name: Run Cypress tests
-                  command: |
-                      npx cypress run \
-                         --spec 'cypress/integration/todosApp/*'  \
-                         \
-                         --record \
-                           \
-                           --parallel  \
-                  working_directory: ''
-            - store_artifacts:
-                  path: cypress/videos
-            - store_artifacts:
-                  path: cypress/screenshots
-            - store_artifacts:
-                  path: results
-    WebdriverIO tests:
-        docker:
-            - image: circleci/node:10
-        steps:
-            - attach_workspace:
-                  at: ~/
-            - run:
-                  name: Start
-                  command: npm run start
-                  background: true
-                  working_directory: ''
-            - run:
-                  name: Run wdio tests
-                  command: npm run test:wdio
-                  working_directory: ''
-      Combine test results:
-        steps: 
-            - attach_workspace:
-                  at: ~/
-            - run: 
-                  name: Merge reports
-                  command: npm run merge-reports
-                  working_directory: ''
-            - store_test_results: 
-                  path: ./merged-results.xml
+  cypress/install:
+    docker:
+      - image: cypress/base:10
+    steps:
+      - checkout
+      - restore_cache:
+          keys:
+            - cache-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
+      - run:
+          name: Check if package-lock.json exists
+          command: |
+            if [ ! -e ./package-lock.json ]; then
+              echo "The Cypress orb uses 'npm ci' to install 'node_modules', which requires a 'package-lock.json'."
+              echo "A 'package-lock.json' file was not found. Please run 'npm install' in your project,"
+              echo "and commit 'package-lock.json' to your repo."
+              exit 1
+            fi
+            working_directory: ''
+      - run:
+          name: Npm CI
+          command: npm ci
+          working_directory: ''
+      - run:
+          command: npx cypress verify
+          working_directory: ''
+      - save_cache:
+          key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
+          paths:
+            - ~/.npm
+            - ~/.cache
+      - persist_to_workspace:
+          root: ~/
+          paths:
+            - project
+            - .cache/Cypress
+  Cypress tests:
+    docker:
+      - image: cypress/base:10
+    parallelism: 2
+    steps:
+      - run:
+          command: echo "Assuming dependencies were installed using cypress/install job"
+      - attach_workspace:
+          at: ~/
+      - run:
+          name: Start
+          command: npm run start
+          background: true
+          working_directory: ''
+      - run:
+          name: Run Cypress tests
+          command: |
+            npx cypress run \
+            --spec 'cypress/integration/todosApp/*'  \
+            \
+            --record \
+            \
+            --parallel  \
+          working_directory: ''
+      - store_artifacts:
+          path: cypress/videos
+      - store_artifacts:
+          path: cypress/screenshots
+      - store_artifacts:
+          path: results
+  WebdriverIO tests:
+    docker:
+      - image: circleci/node:10
+    steps:
+      - attach_workspace:
+          at: ~/
+      - run:
+          name: Start
+          command: npm run start
+          background: true
+          working_directory: ''
+      - run:
+          name: Run wdio tests
+          command: npm run test:wdio
+          working_directory: ''
+  Combine test results:
+    docker:
+      - image: circleci/node:10
+    steps:
+      - attach_workspace:
+          at: ~/
+      - run:
+          name: Merge reports
+          command: npm run merge-reports
+          working_directory: ''
+      - store_test_results:
+          path: ./merged-results.xml
 workflows:
-    build:
-        jobs:
+  build:
+    jobs:
+      - cypress/install
+      - Cypress tests:
+          requires:
             - cypress/install
-            - Cypress tests:
-                  requires:
-                      - cypress/install
-            - WebdriverIO tests:
-                  requires:
-                      - cypress/install
-            - Combine test results:
-                  requires:
-                        - Cypress tests
-                        - WebdriverIO tests               
-    version: 2
+      - WebdriverIO tests:
+          requires:
+            - cypress/install
+      - Combine test results:
+          requires:
+            - Cypress tests
+            - WebdriverIO tests
+  version: 2
